apiVersion: v1
kind: Service
metadata:
  name: zwf-allianceapi-mysql                 #[user][project][app]
  labels:
    user: zwf
    project: allianceapi
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    user: zwf
    project: allianceapi
    app: mysql
  #clusterIP: None


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zwf-allianceapi-mysql                #[user][project][app]
  labels:
    user: zwf
    project: allianceapi
    app: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        user: zwf
        project: allianceapi
        app: mysql
    spec:
      restartPolicy: Always
      containers:
      - name: zwf-allianceapi-mysql-mysql       #[user][project][app][image]
        image: bijiben:5000/mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "111111"
        ports:
        - containerPort: 3306
        ## mount mysql init script
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: zwf-allianceapi-mysql               # must be the same with name in volumes
          readOnly: true
      volumes:
      - name: zwf-allianceapi-mysql                 #[user][project][app]
        nfs:
          path: /opt/data/alliance_api/mysql
          readOnly: true
          server: bijiben                           #here is nfs server addr
