apiVersion: v1
kind: Service
metadata:
  name: zwf-allianceapi-redis                       #[user]-[project]-[app]
  labels:
    user: zwf
    project: allianceapi
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    user: zwf
    project: allianceapi
    app: redis
  #clusterIP: None

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zwf-allianceapi-redis                       # [user]-[project]-[app]
  labels:
    user: zwf
    project: allianceapi
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        user: zwf
        project: allianceapi
        app: redis
    spec:
      restartPolicy: Always
      containers:
      - name: zwf-allianceapi-redis-redis           # [user]-[project]-[app]-[image]
        image: bijiben:5000/redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
