apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
  namespace: default
spec:
  containers:
  - image: centos:kube
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: my-busybox
  restartPolicy: Never
